_wandb:
    value:
        cli_version: 0.23.1
        e:
            9k7h52buhsd52agpad3j8b38yd7oiu18:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M5
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "11811160064"
                codePath: /Users/michellerohrer/Code/Deep_Learning/training.ipynb
                codePathLocal: training.ipynb
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994610155520"
                        used: "116599066624"
                email: michelle.rohrer18@gmail.com
                executable: /Users/michellerohrer/Code/Deep_Learning/.venv/bin/python
                git:
                    commit: 2e11b984e99212f01bb491b80f2e9ad86a9cff6a
                    remote: git@github.com:michelle-rohrer/Deep_Learning.git
                host: macbook-pro.home
                memory:
                    total: "17179869184"
                os: macOS-26.2-arm64-arm-64bit-Mach-O
                program: /Users/michellerohrer/Code/Deep_Learning/training.ipynb
                python: CPython 3.13.11
                root: /Users/michellerohrer/Code/Deep_Learning
                startedAt: "2026-01-20T18:12:48.169239Z"
                writerId: 9k7h52buhsd52agpad3j8b38yd7oiu18
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.11
            "5": 0.23.1
            "8":
                - 1
            "12": 0.23.1
            "13": darwin-arm64
architecture:
    value: BaselineCNN
batch_size:
    value: 32
dataset:
    value: FER-2013
learning_rate:
    value: 0.01
momentum:
    value: 0
num_epochs:
    value: 60
optimizer:
    value: SGD
